### ISSUE TITLE
A build instruction in README, please?

### ISSUE THREAD

**Issue by dmikushin** [golemfactory/golem-hyperdrive#35]
Hi,

Could you please kindly add a couple of lines on how to build the code in repository? For those who are not familiar with Node.

Thanks!

**Comment by jiivan** [comment]
Hey @dmikushin, thanks for reaching out! This repository is not used anymore. Please head to https://github.com/golemfactory/simple-transfer

**Comment by dmikushin** [comment]
Golem's develop branch complains about missing `hyperg` executable. But the
new repository you've pointed to provides `hyperg_cli`, and I don't see how
to make it compatible. Am I missing somethings?

Thanks!

пн, 21 окт. 2019 г. в 12:19, Dariusz Rybi <notifications@github.com>:

**Comment by jiivan** [comment]
Have you tried  getting it from https://github.com/golemfactory/simple-transfer/releases ?

**Comment by dmikushin** [comment]
Got it, thanks!

пн, 21 окт. 2019 г. в 12:47, Dariusz Rybi <notifications@github.com>:
